PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
SELECT distinct(?x) WHERE{

?x dbo:director ?d.
?d dbo:birthPlace ?p. 
?p dbo:country ?c. 
?c dbo:capital ?cap. 

}

