PREFIX dbo:<http://dbpedia.org/ontology/> 
PREFIX dbr:<http://dbpedia.org/resource/>

SELECT * WHERE{

#{?x a dbo:Person .}
#MINUS{ 
#{

?x a dbo:Person . 
FILTER NOT EXISTS {
?x dbo:child ?c .
}



#}
#UNION{
#?x a dbo:Person . 
#?x dbo:child ?c .
#?c dbo:birthPlace ?p.
#?p a dbo:Place.
#}
#}
#}


#SELECT * WHERE{
#?x a dbo:Film . 
#FILTER NOT EXISTS{
#?x dbo:child ?c .
#?c dbo:BirthPlace ?p.
#FILTER NOT EXISTS {
#?p a dbo:Place.
#}
#}
#}

#}}
#{{
#FILTER NOT EXISTS{
#
#?m dbo:birthDate ?d .
#}}UNION{
#?x a dbo:Person .
#FILTER NOT EXISTS{
#?x dbo:spouse ?m .
#}
#}
#}}

#?x dbo:director ?p_1.
#?p_1 dbo:birthPlace ?p_2.
#?p_2 dbo:country ?p_3.
#?p_3 dbo:capital ?p_4.}





