PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
SELECT distinct(?x) WHERE{

?x a dbo:Person .
?x dbo:birthName ?p_2.
?x dbo:birthPlace ?p_4.
?x dbo:birthYear ?p_7.
FILTER(
datatype(?p_7) = xsd:gYear)

} 
