PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
SELECT ?x1 WHERE{

?x1 a dbo:Film.

FILTER NOT EXISTS {
 
?x1 dbo:director ?x2.
?x1 dbo:imdbId ?id1.
?x1 dbo:starring ?s1.
 
FILTER NOT EXISTS {
?x1 dbo:imdbId ?n_11.
?x1 dbo:imdbId ?n_12.
FILTER(?n_11 != ?n_12)
}
}

 
?x2 dbo:birthName ?b2.
?x2 dbo:birthYear ?y2.
?x2 dbo:imdbId ?i2.
 
FILTER
( 
datatype(?y2) = xsd:gYear
AND NOT EXISTS {
?x2 dbo:birthYear ?y21 .
?x2 dbo:birthYear ?y22.
FILTER(?y21 != ?y22)
}
AND  NOT EXISTS {
?x2 dbo:activeYearsSartYear ?a21 .
?x2 dbo:activeYearsSartYear ?a22.
FILTER(?a21 != ?a22)
}
)

}

