PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
SELECT DISTINCT ?x1 WHERE{

?x1 a dbo:Film.

FILTER NOT EXISTS {
 
?x1 dbo:director ?x2.
?x1 dbo:imdbId ?id1.
?x1 dbo:starring ?x4.
 
FILTER NOT EXISTS {
?x1 dbo:imdbId ?n_11.
?x1 dbo:imdbId ?n_12.
FILTER(?n_11 != ?n_12)
}


 
?x2 dbo:birthYear ?y2.
?x2 dbo:imdbId ?i2.
 
FILTER
( 
datatype(?y2) = xsd:gYear
AND NOT EXISTS {
?x2 dbo:birthYear ?y21 .
?x2 dbo:birthYear ?y22.
FILTER(?y21 != ?y22)
}
AND  NOT EXISTS {
?x2 dbo:activeYearsSartYear ?a21 .
?x2 dbo:activeYearsSartYear ?a22.
FILTER(?a21 != ?a22)
}
AND NOT EXISTS{
?x2 dbo:birthPlace ?x3.
FILTER NOT EXISTS{

?x3 dbo:country ?c3.
?x3 dbo:populationTotal ?p3.
?x3 foaf:name ?n3.
 
FILTER
( 
datatype(?p3) = xsd:nonNegativeInteger
)
}
}
)

?x4 dbo:occupation dbr:Actor .
?x4 dbo:birthYear ?y4.
 
FILTER
( 
datatype(?y4) = xsd:gYear
AND NOT EXISTS {
?x4 dbo:birthYear ?y41 .
?x4 dbo:birthYear ?y42.
FILTER(?y41 != ?y42)
}
AND NOT EXISTS{
?x4 dbo:birthPlace ?x5.
FILTER NOT EXISTS{

?x5 dbo:country ?c5.
?x5 dbo:populationTotal ?p5.
?x5 foaf:name ?n5.
 
FILTER
( 
datatype(?p5) = xsd:nonNegativeInteger
)
}
}
)



}
}
