PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
SELECT ?x1 WHERE{

?x1 a dbo:Film.

FILTER (NOT EXISTS{

?x1  dbo:producer ?p1.
?p1  a dbo:Company.
} OR NOT EXISTS{

?x1  dbo:producer ?p1.
?p1  a dbo:Person.
FILTER (EXISTS{
?p1 dbo:birthYear ?y
} OR EXISTS{

?p1 dbo:birthDate ?y
})

})
}

 

